language: c

compiler:
  - gcc
  - clang

sudo: required

arch:
  repos:
    - fluid=https://dl.bintray.com/liri/archlinux-develop/$arch/
    - qtgsettings=https://dl.bintray.com/liri/archlinux-develop/$arch/
  packages:
    - qt5-quickcontrols2
    - xorg-server-xvfb
    - clang
    #- clazy-git
  script:
    - export CLAZY_CHECKS="level1"
    - mkdir build
    - if [ "$CC" = "gcc" ]; then cd build && qmake -spec linux-g++ CONFIG+=use_qt_paths ../platformtheme.pro; fi
    #- if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths QMAKE_CXX="clazy" ../platformtheme.pro; fi
    - if [ "$CC" = "clang" ]; then cd build && qmake -spec linux-clang CONFIG+=use_qt_paths ../platformtheme.pro; fi
    - cd build && make -j$(nproc)

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
